### ISSUE TITLE
希望出个文档,java调用

### ISSUE THREAD

**Issue by mingcong1103** [ven-coder/Assists#2]
希望出个文档,java调用

**Comment by ven-coder** [comment]
> 希望出个文档,java调用

精力有限，使用者也不是很多，暂时搁置

**Comment by iyutong** [comment]
我使用ai进行了转Java语法 https://github.com/iyutong/Assists/wiki

**Comment by iyutong** [comment]
希望可以帮助你

**Comment by ven-coder** [comment]
> 我使用ai进行了转Java语法 https://github.com/iyutong/Assists/wiki

谢谢，后续会转为js动态执行

**Comment by iyutong** [comment]
如果能解析json去执行就好了。其实用js调用执行的话其实非常简单，因为js本来就能直接调用java，只需要把接口，注册给js就可以

iyutong520
***@***.***




---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年3月26日(周三) 下午3:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ven-coder/Assists] 希望出个文档,java调用 (Issue #2)


    
我使用ai进行了转Java语法 https://github.com/iyutong/Assists/wiki
  
谢谢，后续会转为js动态执行

&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;
  ven-coder left a comment (ven-coder/Assists#2)
  
我使用ai进行了转Java语法 https://github.com/iyutong/Assists/wiki
  
谢谢，后续会转为js动态执行
 
&mdash;

**Comment by ven-coder** [comment]
> 如果能解析json去执行就好了。其实用js调用执行的话其实非常简单，因为js本来就能直接调用java，只需要把接口，注册给js就可以
> 
> iyutong520
> ***@***.***
> […](#)
> 
> ---原始邮件---
> 发件人: ***@***.***&gt;
> 发送时间: 2025年3月26日(周三) 下午3:14
> 收件人: ***@***.***&gt;;
> 抄送: ***@***.******@***.***&gt;;
> 主题: Re: [ven-coder/Assists] 希望出个文档,java调用 (Issue [#2](https://github.com/ven-coder/Assists/issues/2))
> 
> 
> 
> 我使用ai进行了转Java语法 https://github.com/iyutong/Assists/wiki
> 
> 谢谢，后续会转为js动态执行
> 
> &mdash;
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***&gt;
>   ven-coder left a comment ([ven-coder/Assists#2](https://github.com/ven-coder/Assists/issues/2))
> 
> 我使用ai进行了转Java语法 https://github.com/iyutong/Assists/wiki
> 
> 谢谢，后续会转为js动态执行
> 
> &mdash;
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***&gt;

好的，感谢提出建议

**Comment by iyutong** [comment]
因为你使用的是kt语言，我看不懂，如果用Java语言的话，我还能帮你开发一下。😂

iyutong520
***@***.***




---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年3月26日(周三) 下午4:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ven-coder/Assists] 希望出个文档,java调用 (Issue #2)


    
如果能解析json去执行就好了。其实用js调用执行的话其实非常简单，因为js本来就能直接调用java，只需要把接口，注册给js就可以
 
iyutong520
 @.***
 …
 
---原始邮件---
 发件人: @.&gt;
 发送时间: 2025年3月26日(周三) 下午3:14
 收件人: @.&gt;;
 抄送: @.@.&gt;;
 主题: Re: [ven-coder/Assists] 希望出个文档,java调用 (Issue #2)
 
我使用ai进行了转Java语法 https://github.com/iyutong/Assists/wiki
 
谢谢，后续会转为js动态执行
 
—
 Reply to this email directly, view it on GitHub, or unsubscribe.
 You are receiving this because you commented.Message ID: @.***&gt;
 ven-coder left a comment (ven-coder/Assists#2)
 
我使用ai进行了转Java语法 https://github.com/iyutong/Assists/wiki
 
谢谢，后续会转为js动态执行
 
—
 Reply to this email directly, view it on GitHub, or unsubscribe.
 You are receiving this because you commented.Message ID: @.***&gt;
  
好的，感谢提出建议

&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;
  ven-coder left a comment (ven-coder/Assists#2)
  
如果能解析json去执行就好了。其实用js调用执行的话其实非常简单，因为js本来就能直接调用java，只需要把接口，注册给js就可以
 
iyutong520
 @.***
 …
 
---原始邮件---
 发件人: @.&gt;
 发送时间: 2025年3月26日(周三) 下午3:14
 收件人: @.&gt;;
 抄送: @.@.&gt;;
 主题: Re: [ven-coder/Assists] 希望出个文档,java调用 (Issue #2)
 
我使用ai进行了转Java语法 https://github.com/iyutong/Assists/wiki
 
谢谢，后续会转为js动态执行
 
—
 Reply to this email directly, view it on GitHub, or unsubscribe.
 You are receiving this because you commented.Message ID: @.***&gt;
 ven-coder left a comment (ven-coder/Assists#2)
 
我使用ai进行了转Java语法 https://github.com/iyutong/Assists/wiki
 
谢谢，后续会转为js动态执行
 
—
 Reply to this email directly, view it on GitHub, or unsubscribe.
 You are receiving this because you commented.Message ID: @.***&gt;
  
好的，感谢提出建议
 
&mdash;
